import {useEffect,useState} from "react";
import {api,CareLink,CarePlan,CarePlanInput,RegimenItem} from "../api/client";
const empty:CarePlanInput={diagnosis:"",treatment_goal:"",summary:"",nutrition_guidance:"",avoidances:"",valid_until:""};
const typeName={MEDICINE:"Лекарство",SUPPLEMENT:"БАД",VITAMIN:"Витамин"};
const frequencyName={DAILY:"каждый день",EVERY_OTHER_DAY:"через день",WEEKDAYS:"по будням"};
const slotName={MORNING:"утро",DAY:"день",EVENING:"вечер"};

export default function CarePlanPanel(){
 const [plan,setPlan]=useState<CarePlan|null>(null),[links,setLinks]=useState<CareLink[]>([]),[items,setItems]=useState<RegimenItem[]>([]),[form,setForm]=useState<CarePlanInput>(empty),[edit,setEdit]=useState(false),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 const load=async()=>{const [p,l,r]=await Promise.all([api.carePlan(),api.careLinks(),api.regimen()]);setPlan(p);setLinks(l);setItems(r.filter(item=>item.is_prescribed));setForm(p?{diagnosis:p.diagnosis||"",treatment_goal:p.treatment_goal||"",summary:p.summary,nutrition_guidance:p.nutrition_guidance,avoidances:p.avoidances,valid_until:p.valid_until}:empty);setLoaded(true)};
 useEffect(()=>{void load().catch(()=>setLoaded(true))},[]);
 const hasLink=links.some(link=>link.status==="ACTIVE"||link.status==="PENDING"); const canEdit=!links.some(link=>link.status==="ACTIVE")&&plan?.source!=="CLINICIAN";
 const save=async()=>{setBusy(true);try{const p=await api.saveCarePlan(form);setPlan(p);setEdit(false)}finally{setBusy(false)}};
 if(!loaded||(!plan&&!links.length&&!items.length))return null;
 return <section className="settings-section care-plan full-care-plan"><div className="settings-section-head"><div><span className="settings-kicker">Полное назначение</span><strong>План врача и режим приёма</strong><p>{plan?.source==="CLINICIAN"?"Назначено специалистом. Изменить этот план может только врач.":hasLink?"План появится здесь после сохранения врачом.":"Личный план восстановления."}</p></div>{canEdit&&<button className="btn" onClick={()=>setEdit(v=>!v)}>{edit?"Закрыть":"Добавить"}</button>}</div>
 {edit?<div className="care-plan-form"><label>Контекст<textarea rows={2} value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></label><label>Питание и режим<textarea rows={3} value={form.nutrition_guidance} onChange={e=>setForm({...form,nutrition_guidance:e.target.value})}/></label><label>Ограничения<textarea rows={2} value={form.avoidances} onChange={e=>setForm({...form,avoidances:e.target.value})}/></label><label>Действует до<input type="date" value={form.valid_until} onChange={e=>setForm({...form,valid_until:e.target.value})}/></label><button className="btn primary" disabled={busy} onClick={()=>void save()}>{busy?"Сохраняю…":"Сохранить план"}</button></div>:<>{plan&&<article className="care-prescription-view"><strong>{plan.source==="CLINICIAN"?"Назначение специалиста":"План восстановления"}</strong>{plan.diagnosis&&<p><b>Диагноз / контекст</b>{plan.diagnosis}</p>}{plan.treatment_goal&&<p><b>Цель ведения</b>{plan.treatment_goal}</p>}{plan.summary&&<p><b>Комментарий врача</b>{plan.summary}</p>}{plan.nutrition_guidance&&<p><b>Питание и режим</b>{plan.nutrition_guidance}</p>}{plan.avoidances&&<p><b>Ограничения</b>{plan.avoidances}</p>}{plan.valid_until&&<small>Действует до {plan.valid_until}</small>}</article>}{items.length>0&&<div className="care-prescribed-items"><strong>Назначения и приём</strong>{items.map(item=><article key={item.id}><b>{item.name}</b><span>{typeName[item.item_type]} · {item.dosage||"дозировка не указана"}</span><small>{frequencyName[item.frequency||"DAILY"]} · {item.schedule_slots.map(slot=>slotName[slot]).join(", ")}{item.start_date?` · с ${item.start_date}`:""}{item.end_date?` до ${item.end_date}`:""}</small>{item.notes&&<em>{item.notes}</em>}</article>)}</div>}</>}
 {links.length>0&&<div className="care-links"><strong>Доступ специалиста</strong>{links.map(link=><div key={link.id}><span>{link.first_name||link.username||"Специалист"} · {link.status==="PENDING"?"ожидает подтверждения":link.status==="ACTIVE"?"есть доступ":"доступ закрыт"}</span>{link.status==="PENDING"?<span><button className="text-btn" onClick={async()=>{await api.consentCareLink(link.id,true);await load()}}>Разрешить</button><button className="text-btn danger-text" onClick={async()=>{await api.consentCareLink(link.id,false);await load()}}>Отклонить</button></span>:link.status==="ACTIVE"?<button className="text-btn danger-text" onClick={async()=>{await api.revokeCareLink(link.id);await load()}}>Закрыть доступ</button>:null}</div>)}</div>}</section>;
}