import {useEffect,useState} from "react";
import {api,CarePlanInput,RegimenItem,RegimenSlot} from "../api/client";import ClinicianFollowUpPanel from "./ClinicianFollowUpPanel";

const emptyPlan:CarePlanInput={diagnosis:"",treatment_goal:"",summary:"",nutrition_guidance:"",avoidances:"",valid_until:""};
const emptyRx={name:"",item_type:"MEDICINE" as RegimenItem["item_type"],dosage:"",schedule_slots:["MORNING"] as RegimenSlot[],start_date:new Date().toISOString().slice(0,10),end_date:"",notes:"",frequency:"DAILY" as RegimenItem["frequency"]};
const labels={MEDICINE:"Лекарство",SUPPLEMENT:"БАД",VITAMIN:"Витамин",DAILY:"Каждый день",EVERY_OTHER_DAY:"Через день",WEEKDAYS:"По будням",MORNING:"утро",DAY:"день",EVENING:"вечер"};
const detail=(e:unknown)=>{const raw=e instanceof Error?e.message:"Не удалось сохранить.";try{return JSON.parse(raw).detail||raw}catch{return raw}};

export default function ClinicianCarePanel({patientId,name}:{patientId:number;name:string}){
 const [plan,setPlan]=useState<CarePlanInput>(emptyPlan),[items,setItems]=useState<RegimenItem[]>([]),[rx,setRx]=useState(emptyRx),[editing,setEditing]=useState<number|null>(null),[busy,setBusy]=useState(false),[note,setNote]=useState("");
 const load=async()=>{const [saved,regimen]=await Promise.all([api.clinicianPlan(patientId),api.clinicianRegimen(patientId)]);setPlan(saved?{diagnosis:saved.diagnosis||"",treatment_goal:saved.treatment_goal||"",summary:saved.summary,nutrition_guidance:saved.nutrition_guidance,avoidances:saved.avoidances,valid_until:saved.valid_until}:emptyPlan);setItems(regimen)};
 useEffect(()=>{void load().catch(e=>setNote(detail(e)))},[patientId]);
 const savePlan=async()=>{setBusy(true);setNote("");try{await api.saveClinicianPlan(patientId,plan);setNote("План ведения сохранён. Он доступен пациенту и учитывается дневником.")}catch(e){setNote(detail(e))}finally{setBusy(false)}};
 const draft=async()=>{setBusy(true);setNote("");try{const result=await api.clinicianNutritionDraft(patientId,plan);setPlan({...plan,nutrition_guidance:result.reply});setNote("Черновик ИИ добавлен в поле. Проверьте и сохраните его как назначение.")}catch(e){setNote(detail(e))}finally{setBusy(false)}};
 const toggleSlot=(slot:RegimenSlot)=>setRx(value=>({...value,schedule_slots:value.schedule_slots.includes(slot)?value.schedule_slots.filter(x=>x!==slot):[...value.schedule_slots,slot]}));
 const saveRx=async()=>{if(!rx.name.trim()||!rx.schedule_slots.length)return;setBusy(true);setNote("");try{if(editing)await api.patchClinicianRegimen(patientId,editing,rx);else await api.addClinicianRegimen(patientId,rx);setRx(emptyRx);setEditing(null);await load();setNote("Назначение сохранено. Пациент сможет только отмечать приём.")}catch(e){setNote(detail(e))}finally{setBusy(false)}};
 const editRx=(item:RegimenItem)=>{setEditing(item.id);setRx({name:item.name,item_type:item.item_type,dosage:item.dosage,schedule_slots:item.schedule_slots,start_date:item.start_date,end_date:item.end_date,notes:item.notes,frequency:item.frequency||"DAILY"})};
 return <section className="card clinician-care"><div className="section-head"><div><span className="settings-kicker">Ведение пациента</span><strong>{name}</strong><span>План назначает и редактирует только врач.</span></div></div><article className="care-prescription-view clinician-plan-preview"><strong>Текущее назначение для пациента</strong>{plan.diagnosis&&<p><b>Диагноз / контекст</b>{plan.diagnosis}</p>}{plan.treatment_goal&&<p><b>Цель ведения</b>{plan.treatment_goal}</p>}{plan.nutrition_guidance&&<p><b>Питание и режим</b>{plan.nutrition_guidance}</p>}{plan.avoidances&&<p><b>Ограничения</b>{plan.avoidances}</p>}{!plan.diagnosis&&!plan.treatment_goal&&!plan.nutrition_guidance&&!plan.avoidances&&<p>Заполните план ниже — после сохранения пациент увидит его в профиле.</p>}</article><div className="care-plan-form"><label>Диагноз / клинический контекст<textarea rows={2} value={plan.diagnosis} onChange={e=>setPlan({...plan,diagnosis:e.target.value})} placeholder="Только подтверждённый врачом контекст"/></label><label>Цель ведения<textarea rows={2} value={plan.treatment_goal} onChange={e=>setPlan({...plan,treatment_goal:e.target.value})} placeholder="Например: восстановить регулярность питания и приёма терапии"/></label><label>Комментарий для пациента<textarea rows={2} value={plan.summary} onChange={e=>setPlan({...plan,summary:e.target.value})} placeholder="Что важно понимать пациенту"/></label><div className="row between"><label className="grow">Рекомендации по питанию<textarea rows={4} value={plan.nutrition_guidance} onChange={e=>setPlan({...plan,nutrition_guidance:e.target.value})} placeholder="Врач может написать сам или использовать черновик ИИ"/></label><button className="btn" disabled={busy} onClick={()=>void draft()}>Черновик ИИ</button></div><label>Ограничения и важные условия<textarea rows={2} value={plan.avoidances} onChange={e=>setPlan({...plan,avoidances:e.target.value})} placeholder="Аллергии, исключения, ограничения режима"/></label><label>Действует до<input type="date" value={plan.valid_until} onChange={e=>setPlan({...plan,valid_until:e.target.value})}/></label><button className="btn primary" disabled={busy} onClick={()=>void savePlan()}>Сохранить план ведения</button></div>
 <div className="clinician-prescriptions"><div className="section-head"><div><span className="settings-kicker">Назначения</span><strong>{editing?"Редактирование назначения":"Новое назначение"}</strong></div>{editing&&<button className="text-btn" onClick={()=>{setEditing(null);setRx(emptyRx)}}>Отменить</button>}</div><div className="care-plan-form"><div className="form-grid"><label>Название<input value={rx.name} onChange={e=>setRx({...rx,name:e.target.value})} placeholder="Например: витамин D"/></label><label>Тип<select value={rx.item_type} onChange={e=>setRx({...rx,item_type:e.target.value as RegimenItem["item_type"]})}><option value="MEDICINE">Лекарство</option><option value="SUPPLEMENT">БАД</option><option value="VITAMIN">Витамин</option></select></label><label>Дозировка<input value={rx.dosage} onChange={e=>setRx({...rx,dosage:e.target.value})} placeholder="Например: 1 таблетка / 2000 МЕ"/></label><label>Периодичность<select value={rx.frequency} onChange={e=>setRx({...rx,frequency:e.target.value as RegimenItem["frequency"]})}><option value="DAILY">Каждый день</option><option value="EVERY_OTHER_DAY">Через день</option><option value="WEEKDAYS">По будням</option></select></label><label>Начало<input type="date" value={rx.start_date} onChange={e=>setRx({...rx,start_date:e.target.value})}/></label><label>Окончание<input type="date" value={rx.end_date} onChange={e=>setRx({...rx,end_date:e.target.value})}/></label></div><label>Время приёма<div className="slot-pills">{(["MORNING","DAY","EVENING"] as RegimenSlot[]).map(slot=><button type="button" className={rx.schedule_slots.includes(slot)?"active":""} key={slot} onClick={()=>toggleSlot(slot)}>{labels[slot]}</button>)}</div></label><label>Инструкция<textarea rows={2} value={rx.notes} onChange={e=>setRx({...rx,notes:e.target.value})} placeholder="Например: после еды, запивать водой"/></label><button className="btn primary" disabled={busy||!rx.name.trim()||!rx.schedule_slots.length} onClick={()=>void saveRx()}>{editing?"Сохранить назначение":"Назначить пациенту"}</button></div><div className="clinician-rx-list">{items.filter(item=>item.is_prescribed).map(item=><article key={item.id}><div><b>{item.name}</b><span>{labels[item.item_type]} · {item.dosage||"дозировка не указана"} · {labels[item.frequency||"DAILY"]}</span><small>{item.schedule_slots.map(slot=>labels[slot]).join(", ")}{item.notes?` · ${item.notes}`:""}</small></div><div><button className="admin-icon edit" onClick={()=>editRx(item)}>✎</button><button className="admin-icon remove" onClick={async()=>{await api.deleteClinicianRegimen(patientId,item.id);await load()}}>−</button></div></article>)}{!items.some(item=>item.is_prescribed)&&<p className="muted">Назначений от врача пока нет.</p>}</div></div><ClinicianFollowUpPanel patientId={patientId}/>{note&&<p className={note.startsWith("План")||note.startsWith("Назначение")||note.startsWith("Черновик")?"invite-success":"error"}>{note}</p>}</section>;
}