import {useEffect,useState} from "react";
import {api,CareMetricDefinition,CarePlan,CareRequest} from "../api/client";

const metrics:{code:CareMetricDefinition["code"];label:string;unit:string}[]=[
 {code:"WEIGHT",label:"Вес",unit:"кг"},{code:"PRESSURE_SYS",label:"Давление: верхнее",unit:"мм рт. ст."},{code:"PRESSURE_DIA",label:"Давление: нижнее",unit:"мм рт. ст."},{code:"GLUCOSE",label:"Глюкоза",unit:"ммоль/л"},{code:"PAIN",label:"Боль",unit:"из 10"},{code:"STEPS",label:"Шаги",unit:"шагов"},
];
const topicName:Record<CareRequest["topic"],string>={MEDICINE:"Препарат / назначение",WELLBEING:"Самочувствие",NUTRITION:"Питание",OTHER:"Другое"};
const dateText=(value:string)=>new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString("ru-RU",{day:"numeric",month:"short"});

export default function ClinicianFollowUpPanel({patientId}:{patientId:number}){
 const [definitions,setDefinitions]=useState<CareMetricDefinition[]>([]),[requests,setRequests]=useState<CareRequest[]>([]),[history,setHistory]=useState<CarePlan[]>([]),[answers,setAnswers]=useState<Record<number,string>>({}),[busy,setBusy]=useState(""),[note,setNote]=useState("");
 const load=async()=>{const [d,r,h]=await Promise.all([api.clinicianMetricDefinitions(patientId),api.clinicianRequests(patientId),api.clinicianPlanHistory(patientId)]);setDefinitions(d);setRequests(r);setHistory(h)};
 useEffect(()=>{void load().catch(e=>setNote(e instanceof Error?e.message:"Не удалось загрузить сопровождение."))},[patientId]);
 const configure=async(metric:{code:CareMetricDefinition["code"];label:string;unit:string},active=true)=>{setBusy(metric.code);try{await api.saveClinicianMetricDefinition(patientId,{...metric,is_active:active});await load();setNote(active?"Показатель появился у пациента.":"Показатель скрыт у пациента.")}catch(e){setNote(e instanceof Error?e.message:"Не удалось обновить показатель.")}finally{setBusy("")}};
 const resolve=async(request:CareRequest)=>{setBusy(`request:${request.id}`);try{await api.clinicianResolveRequest(request.id,answers[request.id]||"");setAnswers(values=>({...values,[request.id]:""}));await load();setNote("Ответ сохранён и доступен пациенту.")}catch(e){setNote(e instanceof Error?e.message:"Не удалось закрыть запрос.")}finally{setBusy("")}};
 return <section className="card clinician-followup"><div className="section-head"><div><span className="settings-kicker">Наблюдение</span><strong>Контакт и показатели</strong><span>Врач выбирает, что пациент будет отмечать. Дозировки ИИ не меняет.</span></div></div>
 <div className="clinician-followup-block"><div className="section-head"><div><strong>Показатели для пациента</strong><span>Включайте только то, что действительно нужно наблюдать.</span></div></div><div className="metric-config-list">{metrics.map(metric=>{const active=definitions.find(item=>item.code===metric.code)?.is_active;return <button type="button" key={metric.code} className={active?"enabled":""} disabled={busy===metric.code} onClick={()=>void configure(metric,!active)}><span>{active?"✓":"+"}</span><div><b>{metric.label}</b><small>{metric.unit}</small></div></button>})}</div></div>
 <div className="clinician-followup-block"><div className="section-head"><div><strong>Запросы пациента</strong><span>Сначала новые и требующие внимания.</span></div></div><div className="clinician-request-list">{requests.filter(item=>item.status==="OPEN").map(request=><article key={request.id} className={request.priority==="HIGH"?"high":""}><div><b>{topicName[request.topic]}</b><small>{dateText(request.created_at)} · {request.priority==="HIGH"?"требует внимания":"обычный"}</small></div><p>{request.message}</p><textarea rows={2} value={answers[request.id]||""} onChange={e=>setAnswers(values=>({...values,[request.id]:e.target.value}))} placeholder="Ответ пациенту (необязательно)"/><button className="btn" disabled={busy===`request:${request.id}`} onClick={()=>void resolve(request)}>{busy===`request:${request.id}`?"Сохраняю…":"Отметить решённым"}</button></article>)}{!requests.some(item=>item.status==="OPEN")&&<p className="muted">Открытых запросов нет.</p>}</div></div>
 {history.length>1&&<details className="plan-history clinician-history"><summary>Журнал версий плана <small>{history.length}</small></summary>{history.slice(1).map(plan=><article key={plan.id}><b>{plan.source==="CLINICIAN"?"Сохранено врачом":"Личная версия пациента"}</b><span>{dateText(plan.created_at)}{plan.author_name?` · ${plan.author_name}`:""}</span><p>{plan.summary||plan.treatment_goal||"План обновлён"}</p></article>)}</details>}{note&&<p className={note.includes("появился")||note.includes("скрыт")||note.includes("доступен")?"invite-success":"error"}>{note}</p>}</section>;
}