import {useEffect,useMemo,useState} from "react";
import {api} from "../api/client";
import ClinicianCarePanel from "./ClinicianCarePanel";

const nameOf=(person:any)=>person?.first_name||person?.username||`Пациент ${person?.id||""}`;
const dateText=(value?:string)=>value?new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString("ru-RU",{day:"numeric",month:"short"}):"—";
const stateLabel:Record<string,string>={TAKEN:"принято",SKIPPED:"пропущено",UNCONFIRMED:"нет отметки"};
const statusText:Record<string,string>={ATTENTION:"требует внимания",WATCH:"наблюдение",GOOD:"стабильно"};

function signals(data:any){
 if(!data)return[];
 const result:string[]=[];const adherence=data.adherence||{};
 if(data.requests?.some((item:any)=>item.status==="OPEN"))result.push(`Есть ${data.requests.filter((item:any)=>item.status==="OPEN").length} открытых запрос(а) пациента.`);
 if(adherence.due&&adherence.unconfirmed)result.push(`Без отметки: ${adherence.unconfirmed} из ${adherence.due} запланированных приёмов.`);
 if(data.food_days?.length===0)result.push("За выбранный период нет записей питания.");
 if(data.checkins?.some((item:any)=>item.needs_contact))result.push("Пациент попросил обратить внимание на самочувствие.");
 if(!result.length)result.push("Критичных отклонений в доступных отметках не видно.");
 return result;
}

export default function ClinicianWorkspace({view}:{view:"patients"|"analytics"|"assistant"}){
 const [patients,setPatients]=useState<any[]>([]),[queue,setQueue]=useState<any[]>([]),[patientId,setPatientId]=useState<number|null>(null),[days,setDays]=useState(30),[overview,setOverview]=useState<any>(null),[loading,setLoading]=useState(false),[inviteOpen,setInviteOpen]=useState(false),[username,setUsername]=useState(""),[inviteNote,setInviteNote]=useState(""),[sending,setSending]=useState(false),[review,setReview]=useState(""),[reviewBusy,setReviewBusy]=useState(false);
 const loadPeople=async()=>{const [people,items]=await Promise.all([api.clinicianPatients(),api.clinicianQueue()]);setPatients(people);setQueue(items);setPatientId(current=>current??items[0]?.id??people[0]?.id??null)};
 useEffect(()=>{void loadPeople().catch(()=>undefined)},[]);
 useEffect(()=>{if(!patientId)return;setLoading(true);api.clinicianOverview(patientId,days).then(setOverview).catch(()=>setOverview(null)).finally(()=>setLoading(false))},[patientId,days]);
 const selected=patients.find(item=>item.id===patientId)||queue.find(item=>item.id===patientId);const selectedQueue=queue.find(item=>item.id===patientId);const notes=useMemo(()=>signals(overview),[overview]);
 const invite=async()=>{if(!username.trim())return;setSending(true);setInviteNote("");try{const result=await api.invitePatient(username.trim());setInviteNote(result.message);setUsername("")}catch(e){try{setInviteNote(JSON.parse(e instanceof Error?e.message:"{}").detail||"Не удалось отправить приглашение.")}catch{setInviteNote(e instanceof Error?e.message:"Не удалось отправить приглашение.")}}finally{setSending(false)}};
 const runReview=async()=>{if(!patientId||reviewBusy)return;setReviewBusy(true);setReview("");try{const result=await api.clinicianAiReview(patientId);setReview(result.reply||"ИИ не вернул текстовый черновик.")}catch(e){setReview(e instanceof Error?e.message:"Не удалось подготовить черновик ИИ.")}finally{setReviewBusy(false)}};
 const title=view==="patients"?"Пациенты":view==="analytics"?"Аналитика пациента":"Помощник специалиста";
 return <><section className="card clinician-hero"><div><span>Режим врача</span><strong>{title}</strong><p>Только пациенты, которые подтвердили доступ. Сначала показываем отклонения, а не весь поток дневников.</p></div><button className="btn primary" onClick={()=>{setInviteOpen(true);setInviteNote("")}}>Пригласить пациента</button></section>
 {queue.length>0&&<section className="card clinician-queue"><div className="section-head"><div><strong>Очередь внимания</strong><span>Зелёные — без заметных сигналов, остальные требуют просмотра.</span></div><button className="text-btn" onClick={()=>void loadPeople()}>Обновить</button></div><div className="queue-list">{queue.map(item=><button key={item.id} className={`queue-item ${item.priority.toLowerCase()} ${patientId===item.id?"selected":""}`} onClick={()=>setPatientId(item.id)}><span className="queue-dot"/><div><b>{nameOf(item)}</b><small>{item.alerts?.[0]||"Нет новых отклонений"}</small></div><em>{statusText[item.priority]}</em></button>)}</div></section>}
 {!patients.length&&!queue.length?<section className="card empty-state"><p>Подтверждённых пациентов пока нет. Пригласите человека по его Telegram username — он сам подтвердит доступ.</p></section>:<><section className="card clinician-controls"><select value={patientId||""} onChange={e=>setPatientId(Number(e.target.value))}>{(patients.length?patients:queue).map(item=><option key={item.id} value={item.id}>{nameOf(item)}</option>)}</select>{view!=="patients"&&<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 дней</option><option value={30}>30 дней</option><option value={90}>90 дней</option><option value={365}>Всё время</option></select>}</section>{loading&&<div className="loading">Обновляем данные пациента…</div>}
 {view==="patients"&&patientId&&<><section className="clinician-patient-glance"><span><b>{nameOf(selected)}</b><small>{selectedQueue?`${statusText[selectedQueue.priority]} · соблюдение ${selectedQueue.adherence?.rate??"—"}%`:"доступ подтверждён"}</small></span>{selectedQueue?.open_requests?<span className="glance-alert">Запросов: {selectedQueue.open_requests}</span>:null}</section><ClinicianCarePanel patientId={patientId} name={nameOf(selected)}/></>}
 {view==="analytics"&&<section className="clinician-analytics"><div className="analytics-summary clinician-summary"><div className="summary-tile"><span>Дней с дневником</span><strong>{overview?.food_days?.length||0}</strong><small>за выбранный период</small></div><div className="summary-tile"><span>Соблюдение приёма</span><strong>{overview?.adherence?.rate??"—"}{overview?.adherence?.rate!==null&&overview?.adherence?.rate!==undefined?"%":""}</strong><small>{overview?.adherence?.taken||0} отмечено из {overview?.adherence?.due||0}</small></div><div className="summary-tile"><span>Самочувствие</span><strong>{overview?.checkins?.length||0}</strong><small>отметок пациента</small></div></div><section className="card clinician-timeline"><div className="section-head"><div><strong>Картина наблюдения</strong><span>Факты из дневника, приёма и отметок пациента.</span></div></div>{overview?.food_days?.slice(0,7).map((item:any)=><div className="timeline-row" key={`food-${item.date}`}><span>{dateText(item.date)}</span><b>Питание: {item.entries} записей · {item.calories||0} ккал</b></div>)}{overview?.regimen?.slice(0,12).map((item:any,index:number)=><div className={`timeline-row regimen ${item.status.toLowerCase()}`} key={`${item.date}-${item.name}-${index}`}><span>{dateText(item.date)}</span><b>{item.name} · {item.slot} · {stateLabel[item.status]}</b>{item.skip_reason&&<small>{item.skip_reason}</small>}</div>)}{overview?.metrics?.slice(0,8).map((item:any)=><div className="timeline-row metric" key={`${item.code}-${item.date}`}><span>{dateText(item.date)}</span><b>{item.label||item.code}: {item.value} {item.unit||""}</b></div>)}{overview?.checkins?.slice(0,5).map((item:any)=><div className={`timeline-row checkin ${item.needs_contact?"contact":""}`} key={`checkin-${item.date}`}><span>{dateText(item.date)}</span><b>Сон: {item.sleep_quality||"—"}/5 {item.needs_contact?"· просит связаться":""}</b>{item.symptoms&&<small>{item.symptoms}</small>}</div>)}{!overview&&<p className="muted">Выберите пациента, чтобы увидеть данные.</p>}</section></section>}
 {view==="assistant"&&<section className="card clinician-ai"><div className="section-head"><div><strong>Короткий разбор</strong><span>Подсказка по фактам, не диагноз и не замена клинического решения.</span></div><button className="btn" disabled={reviewBusy||!patientId} onClick={()=>void runReview()}>{reviewBusy?"Готовлю…":"Черновик ИИ"}</button></div>{notes.map(note=><p key={note}>• {note}</p>)}{overview?.adherence?.skip_reasons&&Object.keys(overview.adherence.skip_reasons).length>0&&<p>• Причины отмеченных пропусков: {Object.entries(overview.adherence.skip_reasons).map(([key,value])=>`${key}: ${value}`).join(", ")}.</p>}{review&&<article className="clinician-ai-draft"><b>Черновик ИИ · проверьте перед использованием</b><p>{review}</p></article>}<div className="assistant-boundary">Проверьте контекст пациента перед любым изменением плана или назначений.</div></section>}</>}
 {inviteOpen&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setInviteOpen(false)}}><section className="modal-card doctor-invite" role="dialog" aria-modal="true"><div className="modal-title"><div><span className="settings-kicker">Новый пациент</span><strong>Пригласить пациента</strong></div><button className="text-btn" onClick={()=>setInviteOpen(false)}>Закрыть</button></div><label>Telegram username пациента<input value={username} onChange={event=>setUsername(event.target.value)} placeholder="@username" maxLength={33}/></label><p className="muted">Приглашение уйдёт только человеку, который уже открыл Food Diary. Пациент сам подтвердит доступ в боте или профиле.</p>{inviteNote&&<p className={inviteNote.startsWith("Приглашение")?"invite-success":"error"}>{inviteNote}</p>}<div className="modal-actions"><button className="btn" onClick={()=>setInviteOpen(false)}>Отмена</button><button className="btn primary" disabled={sending||!username.trim()} onClick={()=>void invite()}>{sending?"Отправляю…":"Отправить приглашение"}</button></div></section></div>}</>;
}