import {useEffect,useMemo,useState} from "react";
import {api} from "../api/client";
import ClinicianCarePanel from "./ClinicianCarePanel";

const flags=(data:any)=>{if(!data)return[];const days=new Set(data.food_days.map((x:any)=>x.date));const missed=data.regimen.filter((x:any)=>!x.taken).length;const taken=data.regimen.filter((x:any)=>x.taken).length;return [`Дневник: ${days.size} дней с записями`, `Назначения: ${taken} отмечено, ${missed} пропущено`,data.plan?"Есть действующий план специалиста":"План не заполнен"];};
const errorText=(e:unknown)=>{const raw=e instanceof Error?e.message:"Не удалось отправить приглашение.";try{return JSON.parse(raw).detail||raw}catch{return raw}};

export default function ClinicianWorkspace({view}:{view:"patients"|"analytics"|"assistant"}){
 const [patients,setPatients]=useState<any[]>([]),[patient,setPatient]=useState<number|null>(null),[days,setDays]=useState(30),[data,setData]=useState<any>(null);
 const [inviteOpen,setInviteOpen]=useState(false),[inviteUsername,setInviteUsername]=useState(""),[inviteNote,setInviteNote]=useState(""),[sending,setSending]=useState(false);
 const loadPatients=()=>api.clinicianPatients().then(v=>{setPatients(v);setPatient(current=>current??v[0]?.id??null)}).catch(()=>undefined);
 useEffect(()=>{void loadPatients()},[]);useEffect(()=>{if(patient)api.clinicianOverview(patient,days).then(setData).catch(()=>setData(null))},[patient,days]);const notes=useMemo(()=>flags(data),[data]);
 const invite=async()=>{if(!inviteUsername.trim())return;setSending(true);setInviteNote("");try{const result=await api.invitePatient(inviteUsername.trim());setInviteNote(result.message);setInviteUsername("")}catch(e){setInviteNote(errorText(e))}finally{setSending(false)}};
 const title=view==="patients"?"Пациенты":view==="analytics"?"Аналитика пациента":"Ассистент специалиста";
 return <><section className="card clinician-hero"><div><span>Режим врача</span><strong>{title}</strong><p>Показываются только пациенты с подтверждённым доступом.</p></div><button className="btn primary" onClick={()=>{setInviteOpen(true);setInviteNote("")}}>Пригласить пациента</button></section>
 {patients.length?<section className="card clinician-controls"><select value={patient||""} onChange={e=>setPatient(Number(e.target.value))}>{patients.map(p=><option key={p.id} value={p.id}>{p.first_name||p.username||`Пациент ${p.id}`}</option>)}</select>{view!=="patients"&&<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 дней</option><option value={30}>30 дней</option><option value={90}>90 дней</option><option value={365}>Всё время</option></select>}</section>:null}
 {!patients.length?<section className="card empty-state"><p>Подтверждённых пациентов пока нет. Пригласите пациента по его Telegram username.</p></section>:view==="patients"?<><section className="card clinician-list">{patients.map(p=><button key={p.id} className={patient===p.id?"selected":""} onClick={()=>setPatient(p.id)}><b>{p.first_name||p.username||`Пациент ${p.id}`}</b><span>Доступ подтверждён</span></button>)}</section>{patient&&<ClinicianCarePanel patientId={patient} name={patients.find(p=>p.id===patient)?.first_name||patients.find(p=>p.id===patient)?.username||`Пациент ${patient}`}/>}</>:view==="analytics"?<><section className="analytics-summary clinician-summary"><div className="summary-tile"><span>Дней с дневником</span><strong>{data?.food_days.length||0}</strong><small>за выбранный период</small></div><div className="summary-tile"><span>Отметки приёма</span><strong>{data?.regimen.filter((x:any)=>x.taken).length||0}</strong><small>выполнено</small></div></section><section className="card clinician-timeline"><strong>Питание и назначения</strong>{data?.food_days.slice(0,14).map((x:any)=><div key={x.date}><span>{x.date}</span><b>{x.entries} записей · {x.calories} ккал</b></div>)}<div className="regimen-review">{data?.regimen.slice(0,18).map((x:any,i:number)=><span key={i} className={x.taken?"taken":"missed"}>{x.date} · {x.name} · {x.slot} {x.taken?"✓":"не отмечено"}</span>)}</div></section></>:<section className="card clinician-ai"><strong>Наблюдения по пациенту</strong>{notes.map(n=><p key={n}>• {n}</p>)}<small>Ассистент фиксирует факты и отклонения от плана; не ставит диагнозы и не меняет назначения.</small></section>}
 {inviteOpen&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setInviteOpen(false)}}><section className="modal-card doctor-invite" role="dialog" aria-modal="true"><div className="modal-title"><div><span className="settings-kicker">Новый пациент</span><strong>Пригласить пациента</strong></div><button className="text-btn" onClick={()=>setInviteOpen(false)}>Закрыть</button></div><label>Telegram username пациента<input value={inviteUsername} onChange={e=>setInviteUsername(e.target.value)} placeholder="@username" maxLength={33}/></label><p className="muted">Приглашение можно отправить только человеку, который уже открыл Food Diary. Он получит сообщение в боте и сам подтвердит доступ.</p>{inviteNote&&<p className={inviteNote.startsWith("Приглашение")?"invite-success":"error"}>{inviteNote}</p>}<div className="modal-actions"><button className="btn" onClick={()=>setInviteOpen(false)}>Отмена</button><button className="btn primary" disabled={sending||!inviteUsername.trim()} onClick={()=>void invite()}>{sending?"Отправляю…":"Отправить приглашение"}</button></div></section></div>}
 </>;
}