import {useEffect,useState} from "react";
import {api,CareCheckin,CareLink,CareMetricDefinition,CareMetricEntry,CarePlan,CareRequest} from "../api/client";

const today=()=>new Intl.DateTimeFormat("en-CA").format(new Date());
const topics:{value:CareRequest["topic"];label:string}[]=[{value:"MEDICINE",label:"Препарат или назначение"},{value:"WELLBEING",label:"Самочувствие"},{value:"NUTRITION",label:"Питание"},{value:"OTHER",label:"Другое"}];
const formatDate=(value:string)=>new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString("ru-RU",{day:"numeric",month:"short"});

export default function PatientFollowUpPanel(){
 const [links,setLinks]=useState<CareLink[]>([]),[checkin,setCheckin]=useState<CareCheckin>({date:today(),sleep_quality:null,symptoms:"",note:"",needs_contact:false}),[requests,setRequests]=useState<CareRequest[]>([]),[definitions,setDefinitions]=useState<CareMetricDefinition[]>([]),[entries,setEntries]=useState<CareMetricEntry[]>([]),[history,setHistory]=useState<CarePlan[]>([]),[metricValues,setMetricValues]=useState<Record<string,string>>({}),[requestOpen,setRequestOpen]=useState(false),[request,setRequest]=useState<{topic:CareRequest["topic"];message:string;priority:"NORMAL"|"HIGH"}>({topic:"WELLBEING",message:"",priority:"NORMAL"}),[busy,setBusy]=useState(""),[note,setNote]=useState("");
 const active=links.find(link=>link.status==="ACTIVE");
 const load=async()=>{const [l,c,r,m,h]=await Promise.all([api.careLinks(),api.careCheckin(),api.careRequests(),api.careMetrics(),api.carePlanHistory()]);setLinks(l);setCheckin(c);setRequests(r);setDefinitions(m.definitions.filter(item=>item.is_active));setEntries(m.entries);setHistory(h)};
 useEffect(()=>{void load().catch(()=>undefined)},[]);
 const saveCheckin=async()=>{setBusy("checkin");setNote("");try{await api.saveCareCheckin(checkin);setNote("Отметка состояния сохранена для вас и специалиста.");await load()}catch(e){setNote(e instanceof Error?e.message:"Не удалось сохранить отметку.")}finally{setBusy("")}};
 const sendRequest=async()=>{if(!request.message.trim())return;setBusy("request");setNote("");try{await api.createCareRequest(request);setRequestOpen(false);setRequest({topic:"WELLBEING",message:"",priority:"NORMAL"});setNote("Запрос отправлен специалисту. Ответ появится в этом разделе.");await load()}catch(e){setNote(e instanceof Error?e.message:"Не удалось отправить запрос.")}finally{setBusy("")}};
 const saveMetric=async(definition:CareMetricDefinition)=>{const value=Number(metricValues[definition.code]);if(!Number.isFinite(value))return;setBusy(`metric:${definition.code}`);try{await api.addCareMetric({code:definition.code,value});setMetricValues(values=>({...values,[definition.code]:""}));await load()}catch(e){setNote(e instanceof Error?e.message:"Не удалось сохранить показатель.")}finally{setBusy("")}};
 if(!active)return null;
 return <section className="settings-section follow-up-panel"><div className="settings-section-head"><div><span className="settings-kicker">Сопровождение</span><strong>Связь с врачом</strong><p>Короткие отметки помогают врачу видеть динамику между консультациями. Это не экстренная связь.</p></div></div><div className="care-safety-note"><b>Важно:</b> при экстренных симптомах обратитесь в местную службу помощи или к врачу напрямую, не ждите ответа в приложении.</div>
 <div className="follow-up-block"><div className="section-head"><div><strong>Как вы сегодня?</strong><span>Сон, самочувствие и один важный комментарий.</span></div></div><div className="sleep-scale"><span>Сон</span>{[1,2,3,4,5].map(value=><button type="button" key={value} className={checkin.sleep_quality===value?"active":""} onClick={()=>setCheckin({...checkin,sleep_quality:value})}>{value}</button>)}<small>{checkin.sleep_quality?(["","очень плохо","ниже обычного","нормально","хорошо","отлично"][checkin.sleep_quality]):"не отмечено"}</small></div><label>Что изменилось или беспокоит?<textarea rows={2} value={checkin.symptoms} onChange={e=>setCheckin({...checkin,symptoms:e.target.value})} placeholder="Необязательно: например, усталость после обеда"/></label><label>Комментарий для себя и врача<textarea rows={2} value={checkin.note} onChange={e=>setCheckin({...checkin,note:e.target.value})} placeholder="Необязательно"/></label><label className="check-label"><input type="checkbox" checked={Boolean(checkin.needs_contact)} onChange={e=>setCheckin({...checkin,needs_contact:e.target.checked})}/>Хочу, чтобы врач обратил на это внимание</label><button className="btn" disabled={busy==="checkin"} onClick={()=>void saveCheckin()}>{busy==="checkin"?"Сохраняю…":"Сохранить отметку"}</button></div>
 <div className="follow-up-block"><div className="section-head"><div><strong>Запрос врачу</strong><span>Для вопросов о назначениях, самочувствии или питании.</span></div><button className="text-btn" onClick={()=>setRequestOpen(value=>!value)}>{requestOpen?"Закрыть":"Написать"}</button></div>{requestOpen&&<div className="care-plan-form"><label>Тема<select value={request.topic} onChange={e=>setRequest({...request,topic:e.target.value as CareRequest["topic"]})}>{topics.map(topic=><option key={topic.value} value={topic.value}>{topic.label}</option>)}</select></label><label>Сообщение<textarea rows={3} value={request.message} onChange={e=>setRequest({...request,message:e.target.value})} placeholder="Коротко опишите вопрос"/></label><label className="check-label"><input type="checkbox" checked={request.priority==="HIGH"} onChange={e=>setRequest({...request,priority:e.target.checked?"HIGH":"NORMAL"})}/>Нужно обратить внимание в ближайшее время</label><button className="btn primary" disabled={busy==="request"||!request.message.trim()} onClick={()=>void sendRequest()}>{busy==="request"?"Отправляю…":"Отправить врачу"}</button></div>}<div className="care-request-list">{requests.slice(0,4).map(item=><article key={item.id} className={item.status==="OPEN"?"open":"resolved"}><div><b>{topics.find(topic=>topic.value===item.topic)?.label||"Запрос"}</b><small>{formatDate(item.created_at)} · {item.status==="OPEN"?"ожидает ответа":"ответ получен"}</small></div><p>{item.message}</p>{item.resolution&&<p className="resolution"><b>Ответ специалиста:</b>{item.resolution}</p>}</article>)}{!requests.length&&<p className="muted">Запросов пока нет.</p>}</div></div>
 {definitions.length>0&&<div className="follow-up-block"><div className="section-head"><div><strong>Показатели для контроля</strong><span>Их выбрал врач — отмечайте только то, что актуально.</span></div></div><div className="metric-cards">{definitions.map(definition=>{const latest=entries.find(entry=>entry.code===definition.code);return <article key={definition.code}><div><b>{definition.label}</b><small>{latest?`${latest.value} ${definition.unit} · ${formatDate(latest.date)}`:`Ещё нет отметок · ${definition.unit}`}</small></div><div className="metric-input"><input inputMode="decimal" value={metricValues[definition.code]||""} onChange={e=>setMetricValues(values=>({...values,[definition.code]:e.target.value}))} placeholder={definition.unit}/><button type="button" disabled={busy===`metric:${definition.code}`} onClick={()=>void saveMetric(definition)}>+</button></div></article>})}</div></div>}
 {history.length>1&&<details className="plan-history"><summary>История планов и изменений <small>{history.length}</small></summary>{history.slice(1).map(plan=><article key={plan.id}><b>{plan.source==="CLINICIAN"?"Версия врача":"Личная версия"}</b><span>{formatDate(plan.created_at)}{plan.author_name?` · ${plan.author_name}`:""}</span><p>{plan.summary||plan.treatment_goal||"План обновлён"}</p></article>)}</details>}{note&&<p className={note.startsWith("Отметка")||note.startsWith("Запрос")?"invite-success":"error"}>{note}</p>}</section>;
}