import {useEffect,useState} from "react";
import {api,Profile} from "../api/client";
import SubscriptionAdmin from "./SubscriptionAdmin";
import ProfilePortrait from "./ProfilePortrait";
import RegimenPanel from "./RegimenPanel";import CarePlanPanel from "./CarePlanPanel";import PatientFollowUpPanel from "./PatientFollowUpPanel";import ClinicianPanel from "./ClinicianPanel";

const accentChoices=[{color:"#1f883d",name:"Зелёный"},{color:"#0969da",name:"Синий"},{color:"#7c3aed",name:"Фиолетовый"},{color:"#cf5b2d",name:"Терракотовый"}];
const issues=[{id:"HEART",label:"Сердце и давление"},{id:"DIABETES",label:"Сахар крови"},{id:"JOINTS",label:"Суставы"},{id:"LIVER",label:"Печень"},{id:"TESTOSTERONE",label:"Гормональный баланс"}];
const applyAccent=(color:string)=>{document.documentElement.style.setProperty("--accent",color);localStorage.setItem("fooddiary-accent",color)};

export default function SettingsPage(){
 const [profile,setProfile]=useState<Profile|null>(null); const [careRole,setCareRole]=useState<"USER"|"PATIENT"|"PENDING_PATIENT"|"CLINICIAN"|"ADMIN">("PATIENT"); const [saved,setSaved]=useState(false); const [error,setError]=useState(""); const [accent,setAccent]=useState(()=>localStorage.getItem("fooddiary-accent")||"#1f883d");
 useEffect(()=>{api.profile().then(setProfile).catch(e=>setError(e instanceof Error?e.message:"Ошибка загрузки"));api.careContext().then(v=>setCareRole(v.role)).catch(()=>undefined)},[]);
 if(!profile)return error?<div className="error">{error}</div>:<div className="loading">Загружаем профиль…</div>;
 const selected=new Set(profile.health_issues.split(",").map(x=>x.trim()).filter(Boolean)); const weightGoal=["LOSE","GAIN","MAINTAIN"].includes(profile.goal);
 const toggle=(id:string)=>{const next=new Set(selected);next.has(id)?next.delete(id):next.add(id);setProfile({...profile,health_issues:[...next].join(",")})};
 const save=async()=>{setSaved(false);setError("");try{setProfile(await api.saveProfile(profile));setSaved(true)}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить профиль")}};
 return <><section className="profile-page"><div className="profile-title"><div><strong>Профиль</strong><span>Личные ориентиры, здоровье и режим</span></div><div className="compact-accent" aria-label="Цвет интерфейса">{accentChoices.map(choice=><button key={choice.color} type="button" className={`accent-option ${accent===choice.color?"selected":""}`} style={{"--choice":choice.color} as React.CSSProperties} aria-label={choice.name} onClick={()=>{setAccent(choice.color);applyAccent(choice.color)}}><span/></button>)}</div></div>
 {careRole==="CLINICIAN"&&<section className="doctor-mode-card"><div><span className="settings-kicker">Кабинет специалиста</span><strong>Режим врача</strong><p>Переключает приложение на пациентов, аналитику и ассистента специалиста.</p></div><button className="btn primary" onClick={()=>{localStorage.setItem("fooddiary-doctor-mode","1");location.reload()}}>Открыть кабинет</button></section>}<section className="card profile-overview"><ProfilePortrait profile={profile}/><div className="overview-metrics"><span><small>Вес</small><b>{profile.weight_kg} кг</b></span><span><small>ИМТ</small><b>{profile.bmi}</b></span><span><small>Ориентир</small><b>{Math.round(profile.targets.calories)} ккал</b></span></div></section>
 <section className="settings-section"><div className="settings-section-head"><div><span className="settings-kicker">Моя цель</span><strong>Направление и параметры</strong><p>Нормы рассчитываются из цели, активности и параметров тела.</p></div></div><div className="form-grid"><label>Цель<select value={profile.goal} onChange={e=>setProfile({...profile,goal:e.target.value})}>{[["LOSE","Похудение"],["MAINTAIN","Поддержание веса"],["GAIN","Набор массы"],["TESTOSTERONE","Повышение тестостерона"],["TREATMENT","Лечение и восстановление"]].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Активность<select value={profile.activity_level} onChange={e=>setProfile({...profile,activity_level:e.target.value})}>{[["LOW","Низкая"],["MEDIUM","Средняя"],["HIGH","Высокая"],["ATHLETE","Спортсмен"]].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Пол<select value={profile.gender} onChange={e=>setProfile({...profile,gender:e.target.value})}><option value="MALE">Мужской</option><option value="FEMALE">Женский</option></select></label><label>Возраст<input type="number" value={profile.age} onChange={e=>setProfile({...profile,age:Number(e.target.value)})}/></label><label>Вес, кг<input type="number" value={profile.weight_kg} onChange={e=>setProfile({...profile,weight_kg:Number(e.target.value)})}/></label><label>Рост, см<input type="number" value={profile.height_cm} onChange={e=>setProfile({...profile,height_cm:Number(e.target.value)})}/></label>{weightGoal&&<><label>Целевой вес, кг<input type="number" placeholder="Необязательно" value={profile.target_weight_kg??""} onChange={e=>setProfile({...profile,target_weight_kg:e.target.value?Number(e.target.value):null})}/></label><label>Дата цели<input type="date" value={profile.goal_deadline} onChange={e=>setProfile({...profile,goal_deadline:e.target.value})}/></label></>}</div>{profile.goal==="TREATMENT"&&<p className="treatment-note">В режиме лечения дневник использует нейтральные нормы поддержания и не предлагает изменение веса.</p>}</section>
 <CarePlanPanel/><PatientFollowUpPanel/>{careRole==="CLINICIAN"&&<ClinicianPanel/>} <section className="settings-section"><div className="settings-section-head"><div><span className="settings-kicker">Питание</span><strong>Предпочтения и ограничения</strong><p>Помогают подобрать более подходящие идеи еды и покупок.</p></div></div><div className="diet-style-options"><label className="check-label"><input type="checkbox" checked={profile.vegetarian} onChange={e=>setProfile({...profile,vegetarian:e.target.checked,vegan:e.target.checked?profile.vegan:false})}/>Вегетарианство</label><label className="check-label"><input type="checkbox" checked={profile.vegan} onChange={e=>setProfile({...profile,vegan:e.target.checked,vegetarian:e.target.checked||profile.vegetarian})}/>Веганство</label><label className="check-label"><input type="checkbox" checked={profile.raw_food} onChange={e=>setProfile({...profile,raw_food:e.target.checked})}/>Сыроедение</label></div><label>Предпочтения в питании<textarea rows={2} value={profile.dietary_preferences} onChange={e=>setProfile({...profile,dietary_preferences:e.target.value})} placeholder="Например: без свинины, люблю рыбу, 3 приёма пищи"/></label><label>Аллергии и непереносимости<textarea rows={2} value={profile.allergies} onChange={e=>setProfile({...profile,allergies:e.target.value})} placeholder="Например: орехи, лактоза"/></label></section>
 <section className="settings-section"><div className="settings-section-head"><div><span className="settings-kicker">Здоровье и восстановление</span><strong>Контекст для дневника</strong><p>Это ориентиры для питания, а не диагноз и не замена консультации врача.</p></div></div><div className="chips">{issues.map(i=><button type="button" className="chip" key={i.id} style={{border:selected.has(i.id)?"1px solid var(--accent)":"1px solid transparent"}} onClick={()=>toggle(i.id)}>{i.label}</button>)}</div><label>Анализы и важные показатели<textarea rows={4} value={profile.lab_results} onChange={e=>setProfile({...profile,lab_results:e.target.value})} placeholder="Необязательно: дата, показатель, значение и единицы"/></label><div className="nutrient-settings"><strong>Нутриентные акценты</strong><p>Показываются в фокусе дня как ориентир питания, а не как назначение добавок.</p><div className="chips">{profile.vitamins.map(v=><span className="chip" key={v}>{v}</span>)}</div></div></section>
 <div className="profile-save-wrap"><button className="btn primary profile-save" onClick={()=>void save()}>Сохранить профиль</button>{saved&&<div className="saved">Изменения сохранены</div>}</div>{error&&<div className="error">{error}</div>}</section><RegimenPanel/><SubscriptionAdmin/></>;
}