import { useEffect, useMemo, useState } from "react";
import { api } from "../api/client";

type Role = "USER" | "PATIENT" | "PENDING_PATIENT" | "CLINICIAN" | "ADMIN";
type Subscriber = { id:number; username:string|null; first_name:string|null; trial_ends_at:string; subscription_ends_at:string|null; is_blocked:number };
type AccessUser = { username:string; is_active:number; created_at:string };
type CareUser = { id:number; username:string|null; first_name:string|null; role:Role };
type CareLink = { id:number; status:string; clinician_username:string|null; clinician_name:string|null; patient_username:string|null; patient_name:string|null };
type UserRow = CareUser & { subscription?:Subscriber; invited:boolean; link?:CareLink };

const roleName:Record<Role,string>={ADMIN:"главный администратор",CLINICIAN:"врач",PATIENT:"пациент",PENDING_PATIENT:"ожидает подтверждения",USER:"пользователь"};
const subscriptionText=(person:Subscriber|undefined)=>{
  if(!person) return "ещё не вошёл";
  if(person.is_blocked) return "доступ приостановлен";
  if(person.subscription_ends_at) return `подписка до ${new Date(person.subscription_ends_at).toLocaleDateString("ru-RU")}`;
  return `пробный период до ${new Date(person.trial_ends_at).toLocaleDateString("ru-RU")}`;
};
const usernameOf=(value:string)=>value.trim().replace(/^@/,"");

export default function SubscriptionAdmin() {
  const [enabled,setEnabled]=useState<boolean|null>(null); const [search,setSearch]=useState(""); const [people,setPeople]=useState<Subscriber[]>([]); const [access,setAccess]=useState<AccessUser[]>([]);
  const [care,setCare]=useState<{users:CareUser[];links:CareLink[]}>({users:[],links:[]}); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const [modal,setModal]=useState<"invite"|"edit"|null>(null); const [selected,setSelected]=useState<UserRow|null>(null); const [username,setUsername]=useState(""); const [doctor,setDoctor]=useState(""); const [patient,setPatient]=useState(""); const [assignedDoctor,setAssignedDoctor]=useState(""); const [role,setRole]=useState<"USER"|"CLINICIAN">("USER"); const [days,setDays]=useState("0"); const [blocked,setBlocked]=useState(false);
  const load=async()=>{try{const [mode,subs,allowed,careData]=await Promise.all([api.adminDevelopmentMode(),api.adminSubscriptions(),api.adminAccess(),api.adminCareOverview()]);setEnabled(mode.enabled);setPeople(subs);setAccess(allowed);setCare(careData)}catch{setEnabled(null)}};
  useEffect(()=>{void load()},[]);
  const rows=useMemo<UserRow[]>(()=>care.users.map(user=>{const subscription=people.find(x=>x.id===user.id);const invited=!!(user.username&&access.some(x=>x.username.toLowerCase()===user.username!.toLowerCase()&&x.is_active));const link=care.links.find(x=>(x.patient_username||"").toLowerCase()===(user.username||"").toLowerCase()&&x.status!=="REVOKED");return {...user,subscription,invited,link}}),[care,people,access]);
  if(enabled===null)return null;
  const close=()=>{setModal(null);setSelected(null);setError("");setUsername("");setDoctor("");setPatient("");setAssignedDoctor("");setDays("0")};
  const toggle=async()=>{setBusy(true);try{setEnabled((await api.setAdminDevelopmentMode(!enabled)).enabled)}catch{setError("Не удалось изменить режим.")}finally{setBusy(false)}};
  const openEdit=(user:UserRow)=>{setSelected(user);setRole(user.role==="CLINICIAN"?"CLINICIAN":"USER");setBlocked(!!user.subscription?.is_blocked);setAssignedDoctor("");setDays("0");setModal("edit");setError("")};
  const invite=async()=>{const value=usernameOf(username);if(!value)return;setBusy(true);setError("");try{await api.grantAdminAccess(value);if(role==="CLINICIAN")await api.adminMakeClinician(value);if(doctor&&patient)await api.adminRequestCareLink(doctor,patient);await load();close()}catch(e){setError(e instanceof Error?e.message:"Не удалось открыть доступ.")}finally{setBusy(false)}};
  const saveUser=async()=>{if(!selected)return;setBusy(true);setError("");try{const user=selected;const userName=user.username;if(userName&&user.role!=="ADMIN"){
      if(role==="CLINICIAN"&&user.role!=="CLINICIAN") await api.adminMakeClinician(userName);
      if(role==="USER"&&user.role==="CLINICIAN") await api.adminRemoveClinician(userName);
    }
    if(assignedDoctor&&userName) await api.adminRequestCareLink(assignedDoctor,userName);
    if(user.subscription)await api.adminUpdateSubscription(user.id,blocked,Math.max(0,Number(days)||0));
    await load();close();
  }catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить изменения.")}finally{setBusy(false)}};
  const removeAccess=async(user:UserRow)=>{if(!user.username)return;if(!window.confirm(`Закрыть доступ для @${user.username}? Данные дневника сохранятся.`))return;setBusy(true);setError("");try{await api.revokeAdminAccess(user.username);await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось закрыть доступ.")}finally{setBusy(false)}};
  return <section className="admin-panel unified-admin"><div className="section-head"><div><strong>Пользователи и доступ</strong><span>Роли, доступ к приложению и подписки — в одном месте</span></div><button className="btn primary" onClick={()=>{setModal("invite");setError("")}}>＋ Добавить</button></div>
    <div className="dev-mode-row compact"><div><strong>Режим разработки</strong><p>{enabled?"Подписки и лимиты временно выключены для всех.":"Действуют пробный период и ограничения подписки."}</p></div><button className={`switch ${enabled?"on":""}`} onClick={()=>void toggle()} disabled={busy} aria-pressed={enabled}><span/></button></div>
    {error&&!modal&&<div className="error">{error}</div>}
    <details className="user-directory"><summary>Пользователи <small>{rows.length}</small></summary><input className="user-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Поиск по имени или @username"/><div className="admin-user-list">{rows.filter(user=>`${user.first_name||""} ${user.username||""}`.toLowerCase().includes(search.trim().toLowerCase())).length?rows.filter(user=>`${user.first_name||""} ${user.username||""}`.toLowerCase().includes(search.trim().toLowerCase())).map(user=><article className="admin-user-row" key={user.id}><div className="admin-user-main"><b>{user.first_name||user.username||`Пользователь ${user.id}`}</b><span>{user.username?`@${user.username}`:"Telegram username не задан"}</span></div><div className="admin-user-meta"><i className={`role-badge ${user.role.toLowerCase()}`}>{roleName[user.role]}</i><small>{user.link?`${user.link.clinician_name||user.link.clinician_username||"Врач"} · ${user.link.status==="ACTIVE"?"доступ подтверждён":"запрос ожидает"}`:subscriptionText(user.subscription)}</small></div><div className="admin-user-actions"><button className="admin-icon edit" title="Изменить" aria-label={`Изменить ${user.first_name||user.username||"пользователя"}`} onClick={()=>openEdit(user)}>✎</button>{user.invited&&user.role!=="ADMIN"?<button className="admin-icon remove" title="Закрыть доступ" aria-label={`Закрыть доступ ${user.first_name||user.username||"пользователя"}`} disabled={busy} onClick={()=>void removeAccess(user)}>−</button>:null}</div></article>):<p className="muted">Пользователи появятся после первого входа.</p>}</div></details>
    <details className="admin-links"><summary>Связи врач — пациент <small>{care.links.filter(x=>x.status!=="REVOKED").length}</small></summary>{care.links.filter(x=>x.status!=="REVOKED").length?<div>{care.links.filter(x=>x.status!=="REVOKED").map(link=><span key={link.id}>{link.clinician_name||link.clinician_username||"Врач"} <b>→</b> {link.patient_name||link.patient_username||"Пациент"}<i className={link.status.toLowerCase()}>{link.status==="ACTIVE"?"подтверждено":"ожидает"}</i></span>)}</div>:<p className="muted">Активных запросов пока нет.</p>}</details>
    {modal&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="modal-card admin-modal" role="dialog" aria-modal="true"><div className="modal-title"><div><span className="settings-kicker">{modal==="invite"?"Новый пользователь":"Управление пользователем"}</span><strong>{modal==="invite"?"Открыть доступ":"Изменить доступ и роль"}</strong></div><button className="text-btn" onClick={close} aria-label="Закрыть">Закрыть</button></div>
      {modal==="invite"?<><label>Telegram username<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="@username" maxLength={33}/></label><label>Роль<select value={role} onChange={e=>setRole(e.target.value as "USER"|"CLINICIAN")}><option value="USER">Пользователь</option><option value="CLINICIAN">Врач</option></select></label><details className="admin-optional"><summary>Сразу запросить доступ к пациенту</summary><label>Username врача<input value={doctor} onChange={e=>setDoctor(e.target.value)} placeholder="@doctor"/></label><label>Username пациента<input value={patient} onChange={e=>setPatient(e.target.value)} placeholder="@patient"/></label></details><p className="muted">Пользователь получит собственный дневник после команды /start. Запрос врача станет активным только после подтверждения пациентом.</p></>:selected&&<><div className="admin-modal-person"><b>{selected.first_name||selected.username||`Пользователь ${selected.id}`}</b><span>{selected.username?`@${selected.username}`:"Telegram username не задан"}</span></div>{selected.role!=="ADMIN"?<label>Роль<select value={role} onChange={e=>setRole(e.target.value as "USER"|"CLINICIAN")} disabled={!selected.username||selected.role==="PATIENT"||selected.role==="PENDING_PATIENT"}><option value="USER">Пользователь</option><option value="CLINICIAN">Врач</option></select></label>:<p className="muted">Роль главного администратора задаётся в настройках сервера.</p>}{(selected.role==="PATIENT"||selected.role==="PENDING_PATIENT")&&<p className="admin-hint">Роль пациента появляется только по связи с врачом. {selected.link?.status==="ACTIVE"?"Доступ уже подтверждён.":"Запрос ожидает подтверждения."}</p>}{selected.role!=="ADMIN"&&selected.username&&<details className="admin-optional"><summary>Сделать пациентом врача</summary><label>Врач<select value={assignedDoctor} onChange={e=>setAssignedDoctor(e.target.value)}><option value="">Не менять</option>{care.users.filter(u=>u.role==="CLINICIAN").map(u=><option key={u.id} value={u.username||""}>{u.first_name||u.username||`Врач ${u.id}`}{u.username?` · @${u.username}`:""}</option>)}</select></label><p className="muted">Будет создан запрос. Пользователь станет пациентом только после подтверждения в боте.</p></details>}{selected.subscription&&<><label className="check-label"><input type="checkbox" checked={blocked} onChange={e=>setBlocked(e.target.checked)}/>Приостановить доступ к приложению</label><label>Продлить подписку, дней<input type="number" min="0" max="365" value={days} onChange={e=>setDays(e.target.value)}/></label><small className="muted">Сейчас: {subscriptionText(selected.subscription)}.</small></>}</>}
      {error&&<div className="error">{error}</div>}<div className="modal-actions"><button className="btn" onClick={close}>Отмена</button><button className="btn primary" disabled={busy||(modal==="invite"&&!username.trim())} onClick={()=>void(modal==="invite"?invite():saveUser())}>{busy?"Сохраняю…":modal==="invite"?"Открыть доступ":"Сохранить"}</button></div></section></div>}
  </section>;
}